version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  pufferserver:
    links:
      - redis
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"